# Generated by Django 4.2.10 on 2024-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navg', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finishdate',
            field=models.DateField(),
        ),
    ]
