# Generated by Django 4.2.10 on 2024-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navg', '0003_alter_project_finishdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesurname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('bodytext', models.CharField(max_length=700)),
                ('submitdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to='uploads/% Y/% m/% d/', width_field=250),
        ),
    ]
