# Generated by Django 4.2.10 on 2024-06-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navg', '0005_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
