# Generated by Django 4.2.10 on 2024-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navg', '0006_alter_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('finishdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PastProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('finishdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
